### ISSUE TITLE
TypeError: this is not a typed array

### ISSUE THREAD

**Issue by Inuyasha5689** [phoboslab/jsmpeg#125]
TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/home/inuyasha5689/Desktop/jsmpeg/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/inuyasha5689/Desktop/jsmpeg/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)

**Comment by phoboslab** [comment]
When does this happen? Did it ever work? How did you start the server? How did you start ffmpeg?

**Comment by phoboslab** [comment]
Dup: https://github.com/phoboslab/jsmpeg/issues/129
