### ISSUE TITLE
Issue changing default player parameters

### ISSUE THREAD

**Issue by mwn2017** [phoboslab/jsmpeg#139]
Hello,
I've run the player with the following settings:

`var player = new JSMpeg.Player(url, { canvas: canvas, 
									  pauseWhenHidden: true,
									  maxAudioLag: 0.1,
									  videoBufferSize: 64 * 1024,
									  audioBufferSize: 13 * 1024
									});`

After few seconds of playback video stops (often showing artifacts).
Javascript console shows the following:

`Uncaught RangeError: Source is too large
    at Uint8Array.set (native)
    at BitBuffer.appendSingleBuffer (http://127.0.0.1/js/jsmpeg.min.js:1:10612)
    at BitBuffer.write (http://127.0.0.1/js/jsmpeg.min.js:1:10407)
    at MPEG1.BaseDecoder.write (http://127.0.0.1/js/jsmpeg.min.js:1:21077)
    at MPEG1.write (http://127.0.0.1/js/jsmpeg.min.js:1:22768)
    at TS.packetComplete (http://127.0.0.1/js/jsmpeg.min.js:1:20238)
    at TS.parsePacket (http://127.0.0.1/js/jsmpeg.min.js:1:19365)
    at TS.write (http://127.0.0.1/js/jsmpeg.min.js:1:17519)
    at WSSource.onMessage (http://127.0.0.1/js/jsmpeg.min.js:1:16820)`

This message is probably repeated for every frame.
Also audio stops, but after video.

With the following parameters, everything is fine:

`var player = new JSMpeg.Player(url, { canvas: canvas, pauseWhenHidden: true });`

Thanks

**Comment by phoboslab** [comment]
Well, the buffer size you specified in your first example (`64*1024` = 64kb) is to small to hold a single frame. The default is 512kb.
