### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by x011** [phoboslab/jsmpeg#160]
I'm getting the following error while trying run node `websocket-relay.js pass 8081 8082`

```
/home/pi/node_modules/ws/index.js:9
const WebSocket = require('./lib/WebSocket');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/jsmpeg/websocket-relay.js:9:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Any idea why this is happening ?

**Comment by jvanegas** [comment]
@x011 You have an old version of Node.js in your system.

You have to update Node.js. You can use `n` to do this:
```
sudo npm install -g n
```

and then

```
sudo n latest
```

**Comment by x011** [comment]
Greatly appreciated, raspberrypy jesse came with an old version, you can close this now, thank you !
