### ISSUE TITLE
ERROR RangeError: Source is too large

### ISSUE THREAD

**Issue by hei-pa** [phoboslab/jsmpeg#203]
After some time playing my video from websocket chrome(62.0.3202.75) and firefox are throwing this error on each chunk.

```javascript
ERROR RangeError: Source is too large
    at Uint8Array.set (native)
    at BitBuffer.appendSingleBuffer (http://localhost:4200/scripts.bundle.js:2:10647)
    at BitBuffer.write (http://localhost:4200/scripts.bundle.js:2:10442)
    at TS.write (http://localhost:4200/scripts.bundle.js:2:17491)
    at WSSource.onMessage (http://localhost:4200/scripts.bundle.js:2:16905)
    at WebSocket.wrapFn (webpack-internal:///../../../../zone.js/dist/zone.js:1166:39)
    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:425:31)
    at Object.onInvokeTask (webpack-internal:///../../../core/esm5/core.js:4815:33)
    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:424:36)
    at Zone.runTask (webpack-internal:///../../../../zone.js/dist/zone.js:192:47)
```

**Comment by mojigai** [comment]
I've also had this problem,Have you solved it?

**Comment by CooooSo** [comment]
I got this problem too. Have anyone solved it?
