### ISSUE TITLE
Server broken down when close/refresh view-stream page in Chrome

### ISSUE THREAD

**Issue by elementCarbon** [phoboslab/jsmpeg#214]
I launch the server on Win7 and use Chrome( v63.0.3239.132 64bit) to visit the view-stream page and close, the server broke down with following code: 
New WebSocket Connection:  ::ffff:127.0.0.1 Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36 (1 total)

Disconnected WebSocket (1 total)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)

However, when using other browsers like Firefox/Safari/IE to visit and close, the server keeps fine:

New WebSocket Connection:  ::ffff:127.0.0.1 Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0 (2 total)
Disconnected WebSocket (1 total)

It seems that when launching the server on Linux, all browsers are fine.

**Comment by elementCarbon** [comment]
It seems caused by websockets/ws#1256. WebSocket closing handshake does not work properly when a page is refreshed or closed in the latest version of Chrome (include 65.0.3310.0 canary, 64.0.3282.3 beta 63.0.3239.108 stable, 62.0.3202.94).
