### ISSUE TITLE
  EMPTY_BUFFER: Buffer.alloc(0),

### ISSUE THREAD

**Issue by brizey02** [phoboslab/jsmpeg#236]
/home/boo/node_modules/ws/lib/constants.js:8
  EMPTY_BUFFER: Buffer.alloc(0),
                       ^

TypeError: Buffer.alloc is not a function
    at Object.<anonymous> (/home/chris/node_modules/ws/lib/constants.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/chris/node_modules/ws/lib/permessage-deflate.js:7:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by brizey02** [comment]
Solved, node was a older version.

**Comment by johnlpm** [comment]
Do you update or use the older node version?
