### ISSUE TITLE
Error const { kStatusCode, NOOP } = require('./constants');

### ISSUE THREAD

**Issue by flightxar** [phoboslab/jsmpeg#272]
node websocket-relay.js supersecret 8081 8082
/home/ubuntu/jsmpeg/node_modules/ws/lib/permessage-deflate.js:7
const { kStatusCode, NOOP } = require('./constants');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/jsmpeg/node_modules/ws/lib/websocket.js:11:27)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by phoboslab** [comment]
Update your NodeJS Version.
